version: '3.8'
services:
  web:
    build: .
    network_mode: host
    # CAMBIO IMPORTANTE: --port 80 (Puerto web est√°ndar)
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - ./app:/app:Z
    restart: always
