services:
  - type: web
    name: hotel-roperia
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: DATABASE_URL
        value: /code/data/roperia.db  # This tells the code where to save
      - key: PORT
        value: 80
    disk:
      name: sqlite-storage
      mountPath: /code/data          # This folder survives restarts
      sizeGB: 1